# Build and testing pipeline on Azure.

resources:
  containers:
  - container: wpilib2020
    image: wpilib/roborio-cross-ubuntu:2020-18.04
  - container: raspbian
    image:  wpilib/raspbian-cross-ubuntu:10-18.04
  - container: aarch64
    image:  wpilib/aarch64-cross-ubuntu:bionic-18.04
  - container: ubuntu
    image:  wpilib/ubuntu-base:18.04

variables:
- group: Artifactory-Package-Publish

trigger:
  batch: true
  branches:
    include:
    - master

stages:
- stage: Build
  jobs:
  - template: azure-templates/job-build-vcpkg.yml

  - template: azure-templates/job-build.yml
    parameters:
      jobName: Linux_Arm
      buildOptions: '-Ponlylinuxathena'
      artifactName: 'Athena'

  - template: azure-templates/job-build.yml
    parameters:
      jobName: Linux_Raspbian
      container: raspbian
      buildOptions: '-Ponlylinuxraspbian'
      artifactName: 'Raspbian'

  - template: azure-templates/job-build.yml
    parameters:
      jobName: Linux_Aarch64
      container: aarch64
      buildOptions: '-Ponlylinuxaarch64bionic'
      artifactName: 'Aarch64'

  - template: azure-templates/job-build.yml
    parameters:
      jobName: Linux
      container: ubuntu
      artifactName: 'Linux'

  - template: azure-templates/job-build.yml
    parameters:
      jobName: Windows_64_Bit
      pool:
        vmImage: 'windows-2019'
      container: ''
      jdkVersionOption: '1.11'
      buildOptions: '-PskipPMD'
      artifactName: 'Win64'

  - template: azure-templates/job-build-win32.yml

  - template: azure-templates/job-build-mac.yml

  - template: azure-templates/job-build-cmake.yml

  - template: azure-templates/job-styleguide.yml

- template: azure-templates/stage-combine.yml
  parameters:
    publish: True
    publishUserName: $(PublishUserName)
    publishPassword: $(PublishPassword)
    artifacts: [Mac, Win32, Win64, Linux, Raspbian, Athena, Aarch64]
