# Job for checking wpiformat violations

parameters:
  jobName: ''
  pool:
    vmImage: 'Ubuntu 18.04'

jobs:
- job: Styleguide
  pool: ${{ parameters.pool }}

  container: ubuntu

  workspace:
    clean: all

  timeoutInMinutes: 0

  steps:
    - script: |
        sudo apt-get update -q
        sudo apt-get install gnupg lsb-release software-properties-common -y
        chmod +x azure-templates/clang-format.sh
        sudo ./azure-templates/clang-format.sh 10
        sudo pip3 install wpiformat
      displayName: 'Install wpiformat'

    - script: |
        git checkout -b master
        wpiformat -clang 10
      displayName: 'Run wpiformat'

    - script: |
        # Ensure formatter made no changes
        git --no-pager diff --exit-code HEAD
      displayName: 'Check wpiformat Output'
